### PR TITLE
Added guidelines for contributors

### PR DESCRIPTION
**Pull request by willu47**
Hi @AgnesBelt and @HauHe - I've added these files to the main OSeMOSYS repository to give some guidance to members of the community who would like to contribute to the code, documentation, or find a bug.

Do you think this would have helped with the question earlier today?

### CODE REVIEW

**Comment by AgnesBelt** [comment]
Hi @willu47, definitely these files help a lot. Thank you!

**Comment by willu47** [comment]
> Hi @willu47, definitely these files help a lot. Thank you!

Great @AgnesBelt  - if you're happy, could you approve this pull request, and I will then merge them into the main repository.

**Review by AgnesBelt — APPROVED** [review]

**Comment by HauHe** [comment]
Hi @willu47 , yes that looks very useful! Thanks for putting that together.

**Review by HauHe — APPROVED** [review]

**Comment by willu47** [comment]
Partially completes #36

**Pull request merged**
