### PR TITLE
New reserve margin

### LINKED ISSUE #121: Check that the documentation is updated and the parameter definition so it is not specified as a binary parameter
- [x] Please check that the documentation is updated and the parameter definition so it is not specified as a binary parameter

_Originally posted by @willu47 in https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg/issues/59#issuecomment-1584134528_

### PR DESCRIPTION
**Pull request by HauHe**
This PR addresses #121.

Blocked by  OSeMOSYS/OSeMOSYS_GNU_MathProg#59

### CODE REVIEW

**Review by willu47 — APPROVED** [review]

**Comment by HauHe** [comment]
I think now the documentation is ahead of the code. We didn't merge the new ReserveMargin yet, because the region issue needs to be addressed first. And if we decide drop the set REGION the new ReserveMargin will need adjustments.
Sorry should have flagged this here as well.

**Comment by willu47** [comment]
Okay, can you create another pull request which corrects the issue for the current version (v1.0.1) of the GNU MathProg code?  Typically, you would include an e.g. "deprecated in v1.2.3" message when removing parameters, and an "added in v1.2.3" note when adding new parameters.

**Comment by HauHe** [comment]
Sure, since I will still need to adjust the new reserve margin to work for multiple regions without using the regions set. I would for now create PR that brings the documentation back to the old parameter, but corrects the text on the ReserveMarginTagTechnology, which is not binary as it was wrongly written in the documentation.

**Comment by HauHe** [comment]
Ok, removed the new paramter from the new reserve margin but kept the correction of the description of `ReserveMaringTagTechnology`

**Review by willu47 — APPROVED** [review]

**Comment by willu47** [comment]
Closes #121

**Pull request merged**
